scaling:
  tile:
    1
  mob:
    0.25
  player:
    0.25
window:
  width:
    1920
  height:
    1080
  title:
    Hecate's Dungeon
world:
  cell:
    chance:
      0.4
    death:
      3
    birth:
      4
    steps:
      4
    width:
      400
    height:
      400
  bin:
    width:
      100
    height:
      100