# Level
FLOOR_LENGTH = 60
TEXTURE_SIZE = 64

# Physics
GRAVITY = 1

# Controls
PLAYER_MOVEMENT_SPEED = 5
GROUND_CONTROL = 0.5
AIR_CONTROL = 0.07
JUMP_FORCE = 5
JUMP_FORCE_REDUCTION = 0.8
JUMP_COUNT = 2
JUMP_VELOCITY_BONUS = 0.1
DASH_DISTANCE = 64 * 3
DASH_COUNT = 1

# Named integers
RIGHT = 1
LEFT = -1

# Level-related
BLOCK_LEN = 6

# Camera
VIEWPORT_MARGIN = 200

# Particles
DEFAULT_SCALE = 0.3
PLUME_SCALE = 0.5
LINE_SCALE = 1
DEFAULT_ALPHA = 255
DEFAULT_PARTICLE_LIFETIME = 1.0
PLUME_PARTICLE_LIFETIME = 1.0
LINE_EMIT_INTERVAL = 0.05
PLUME_EMIT_INTERVAL = 0.01
PARTICLE_SPEED_FAST = 10.0
PARTICLE_SPEED_SLOW = 0.3
PLUME_EMIT_DURATION = 0.25
DEFAULT_EMIT_INTERVAL = 0.003
DEFAULT_EMIT_DURATION = 0.5
NUM_COLORS = 25
EXPLOSION_EMIT_INTERVAL = .001
EXPLOSION_NUM_PARTICLE = 25
EXPLOSION_SCALE = 2
EXPLOSION_PARTICLE_LIFETIME = .5
