# Level
FLOOR_LENGTH = 60
FLOOR_TEXTURE_LENGTH = 64

# Physics
GRAVITY = 1

# Controls
PLAYER_MOVEMENT_SPEED = 5
GROUND_CONTROL = 0.5
AIR_CONTROL = 0.07
JUMP_FORCE = 5.5
JUMP_FORCE_REDUCTION = 0.8
JUMP_COUNT = 2
