

WIDTH = 400
HEIGHT = 300

TITLE = "Gaming Jam"

TILE_SIZE = 16
TILE_SIZE_D2 = TILE_SIZE / 2

SQUARE_HIT_BOX = [
    [-TILE_SIZE_D2, -TILE_SIZE_D2],
    [-TILE_SIZE_D2, TILE_SIZE_D2],
    [TILE_SIZE_D2, TILE_SIZE_D2],
    [TILE_SIZE_D2, -TILE_SIZE_D2]
]

RAMP_HIT_BOX_LEFT = [
    [-TILE_SIZE_D2, -TILE_SIZE_D2],
    [TILE_SIZE_D2, -TILE_SIZE_D2],
    [-TILE_SIZE_D2, TILE_SIZE_D2]
]

RAMP_HIT_BOX_RIGHT = [
    [-TILE_SIZE_D2, -TILE_SIZE_D2],
    [TILE_SIZE_D2, -TILE_SIZE_D2],
    [TILE_SIZE_D2, TILE_SIZE_D2],
]

GRAVITY = 0.4

GRID_SIZE = 16

ROOM_WIDTH = 21
ROOM_HEIGHT = 15